-   id: blacken-docs
    name: blacken-docs
    description: Run `black` on python code blocks in documentation files
    entry: blacken-docs
    language: python
    types_or: [rst, markdown, tex, python, pyi, jupyter]
